project:
  type: website
  output-dir: docs
  
website:
  title: "Mohamed Essaied Hamrita"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: facebook
        href: https://facebook.com/
      - icon: github
        href: https://github.com/Hamrita
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2025, Hamrita"

format:
  html:
    theme: cerulean
    toc: true

editor: source

